apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  SECRET_KEY: django-insecure-0if40nf4nf93n4
  DATABASE_URL: postgres://test_k8s:OwOtBep9Frut@my-postgres-postgresql:5432/test_k8s