apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: edu-roman-grachev
spec:
  template:
    metadata:
      name: django-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: django
          image: grroma/django_app:bd7995a
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secret
          command: ["python", "manage.py", "migrate"]